/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BaseSubscriptionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PAUSER_ROLE"
      | "cancelSubscription"
      | "createPlan"
      | "disablePlan"
      | "nextPlanId"
      | "plans"
      | "processPayment"
      | "recoverERC20"
      | "subscribe"
      | "subscribeWithPermit"
      | "updateMerchant"
      | "updatePlan"
      | "userSubscriptions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MerchantUpdated"
      | "PaymentProcessed"
      | "PlanCreated"
      | "PlanDisabled"
      | "PlanUpdated"
      | "Subscribed"
      | "SubscriptionCancelled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPlan",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "disablePlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPlanId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "plans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "processPayment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverERC20",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribeWithPermit",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMerchant",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePlan",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "userSubscriptions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disablePlan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextPlanId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscribeWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMerchant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updatePlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userSubscriptions",
    data: BytesLike
  ): Result;
}

export namespace MerchantUpdatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    oldMerchant: AddressLike,
    newMerchant: AddressLike
  ];
  export type OutputTuple = [
    planId: bigint,
    oldMerchant: string,
    newMerchant: string
  ];
  export interface OutputObject {
    planId: bigint;
    oldMerchant: string;
    newMerchant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentProcessedEvent {
  export type InputTuple = [
    user: AddressLike,
    planId: BigNumberish,
    amount: BigNumberish,
    newNextPaymentDate: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    planId: bigint,
    amount: bigint,
    newNextPaymentDate: bigint
  ];
  export interface OutputObject {
    user: string;
    planId: bigint;
    amount: bigint;
    newNextPaymentDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanCreatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    merchant: AddressLike,
    token: AddressLike,
    tokenDecimals: BigNumberish,
    price: BigNumberish,
    billingCycle: BigNumberish,
    priceInUsd: boolean,
    usdPrice: BigNumberish,
    priceFeedAddress: AddressLike
  ];
  export type OutputTuple = [
    planId: bigint,
    merchant: string,
    token: string,
    tokenDecimals: bigint,
    price: bigint,
    billingCycle: bigint,
    priceInUsd: boolean,
    usdPrice: bigint,
    priceFeedAddress: string
  ];
  export interface OutputObject {
    planId: bigint;
    merchant: string;
    token: string;
    tokenDecimals: bigint;
    price: bigint;
    billingCycle: bigint;
    priceInUsd: boolean;
    usdPrice: bigint;
    priceFeedAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanDisabledEvent {
  export type InputTuple = [planId: BigNumberish];
  export type OutputTuple = [planId: bigint];
  export interface OutputObject {
    planId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanUpdatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    billingCycle: BigNumberish,
    price: BigNumberish,
    priceInUsd: boolean,
    usdPrice: BigNumberish,
    priceFeedAddress: AddressLike
  ];
  export type OutputTuple = [
    planId: bigint,
    billingCycle: bigint,
    price: bigint,
    priceInUsd: boolean,
    usdPrice: bigint,
    priceFeedAddress: string
  ];
  export interface OutputObject {
    planId: bigint;
    billingCycle: bigint;
    price: bigint;
    priceInUsd: boolean;
    usdPrice: bigint;
    priceFeedAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [
    user: AddressLike,
    planId: BigNumberish,
    nextPaymentDate: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    planId: bigint,
    nextPaymentDate: bigint
  ];
  export interface OutputObject {
    user: string;
    planId: bigint;
    nextPaymentDate: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCancelledEvent {
  export type InputTuple = [user: AddressLike, planId: BigNumberish];
  export type OutputTuple = [user: string, planId: bigint];
  export interface OutputObject {
    user: string;
    planId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BaseSubscription extends BaseContract {
  connect(runner?: ContractRunner | null): BaseSubscription;
  waitForDeployment(): Promise<this>;

  interface: BaseSubscriptionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PAUSER_ROLE: TypedContractMethod<[], [string], "view">;

  cancelSubscription: TypedContractMethod<
    [_planId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPlan: TypedContractMethod<
    [
      _merchantAddress: AddressLike,
      _token: AddressLike,
      _price: BigNumberish,
      _billingCycle: BigNumberish,
      _priceInUsd: boolean,
      _usdPrice: BigNumberish,
      _priceFeedAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  disablePlan: TypedContractMethod<
    [_planId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextPlanId: TypedContractMethod<[], [bigint], "view">;

  plans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string,
        boolean
      ] & {
        merchant: string;
        token: string;
        tokenDecimals: bigint;
        price: bigint;
        billingCycle: bigint;
        priceInUsd: boolean;
        usdPrice: bigint;
        priceFeedAddress: string;
        active: boolean;
      }
    ],
    "view"
  >;

  processPayment: TypedContractMethod<
    [_user: AddressLike, _planId: BigNumberish],
    [void],
    "nonpayable"
  >;

  recoverERC20: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<[_planId: BigNumberish], [void], "nonpayable">;

  subscribeWithPermit: TypedContractMethod<
    [
      _planId: BigNumberish,
      _deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  updateMerchant: TypedContractMethod<
    [_planId: BigNumberish, _newMerchant: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePlan: TypedContractMethod<
    [
      _planId: BigNumberish,
      _billingCycle: BigNumberish,
      _price: BigNumberish,
      _priceInUsd: boolean,
      _usdPrice: BigNumberish,
      _priceFeedAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  userSubscriptions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        subscriber: string;
        planId: bigint;
        startTime: bigint;
        nextPaymentDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PAUSER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelSubscription"
  ): TypedContractMethod<[_planId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPlan"
  ): TypedContractMethod<
    [
      _merchantAddress: AddressLike,
      _token: AddressLike,
      _price: BigNumberish,
      _billingCycle: BigNumberish,
      _priceInUsd: boolean,
      _usdPrice: BigNumberish,
      _priceFeedAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disablePlan"
  ): TypedContractMethod<[_planId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextPlanId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "plans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string,
        boolean
      ] & {
        merchant: string;
        token: string;
        tokenDecimals: bigint;
        price: bigint;
        billingCycle: bigint;
        priceInUsd: boolean;
        usdPrice: bigint;
        priceFeedAddress: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "processPayment"
  ): TypedContractMethod<
    [_user: AddressLike, _planId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recoverERC20"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[_planId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscribeWithPermit"
  ): TypedContractMethod<
    [
      _planId: BigNumberish,
      _deadline: BigNumberish,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateMerchant"
  ): TypedContractMethod<
    [_planId: BigNumberish, _newMerchant: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePlan"
  ): TypedContractMethod<
    [
      _planId: BigNumberish,
      _billingCycle: BigNumberish,
      _price: BigNumberish,
      _priceInUsd: boolean,
      _usdPrice: BigNumberish,
      _priceFeedAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userSubscriptions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        subscriber: string;
        planId: bigint;
        startTime: bigint;
        nextPaymentDate: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "MerchantUpdated"
  ): TypedContractEvent<
    MerchantUpdatedEvent.InputTuple,
    MerchantUpdatedEvent.OutputTuple,
    MerchantUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentProcessed"
  ): TypedContractEvent<
    PaymentProcessedEvent.InputTuple,
    PaymentProcessedEvent.OutputTuple,
    PaymentProcessedEvent.OutputObject
  >;
  getEvent(
    key: "PlanCreated"
  ): TypedContractEvent<
    PlanCreatedEvent.InputTuple,
    PlanCreatedEvent.OutputTuple,
    PlanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PlanDisabled"
  ): TypedContractEvent<
    PlanDisabledEvent.InputTuple,
    PlanDisabledEvent.OutputTuple,
    PlanDisabledEvent.OutputObject
  >;
  getEvent(
    key: "PlanUpdated"
  ): TypedContractEvent<
    PlanUpdatedEvent.InputTuple,
    PlanUpdatedEvent.OutputTuple,
    PlanUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCancelled"
  ): TypedContractEvent<
    SubscriptionCancelledEvent.InputTuple,
    SubscriptionCancelledEvent.OutputTuple,
    SubscriptionCancelledEvent.OutputObject
  >;

  filters: {
    "MerchantUpdated(uint256,address,address)": TypedContractEvent<
      MerchantUpdatedEvent.InputTuple,
      MerchantUpdatedEvent.OutputTuple,
      MerchantUpdatedEvent.OutputObject
    >;
    MerchantUpdated: TypedContractEvent<
      MerchantUpdatedEvent.InputTuple,
      MerchantUpdatedEvent.OutputTuple,
      MerchantUpdatedEvent.OutputObject
    >;

    "PaymentProcessed(address,uint256,uint256,uint256)": TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;
    PaymentProcessed: TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;

    "PlanCreated(uint256,address,address,uint8,uint256,uint256,bool,uint256,address)": TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;
    PlanCreated: TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;

    "PlanDisabled(uint256)": TypedContractEvent<
      PlanDisabledEvent.InputTuple,
      PlanDisabledEvent.OutputTuple,
      PlanDisabledEvent.OutputObject
    >;
    PlanDisabled: TypedContractEvent<
      PlanDisabledEvent.InputTuple,
      PlanDisabledEvent.OutputTuple,
      PlanDisabledEvent.OutputObject
    >;

    "PlanUpdated(uint256,uint256,uint256,bool,uint256,address)": TypedContractEvent<
      PlanUpdatedEvent.InputTuple,
      PlanUpdatedEvent.OutputTuple,
      PlanUpdatedEvent.OutputObject
    >;
    PlanUpdated: TypedContractEvent<
      PlanUpdatedEvent.InputTuple,
      PlanUpdatedEvent.OutputTuple,
      PlanUpdatedEvent.OutputObject
    >;

    "Subscribed(address,uint256,uint256)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;

    "SubscriptionCancelled(address,uint256)": TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
    SubscriptionCancelled: TypedContractEvent<
      SubscriptionCancelledEvent.InputTuple,
      SubscriptionCancelledEvent.OutputTuple,
      SubscriptionCancelledEvent.OutputObject
    >;
  };
}
