/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MaliciousToken } from "./MaliciousToken";
export type { MockV3Aggregator } from "./MockV3Aggregator";
export type { PermitToken } from "./PermitToken";
