name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Slither
      run: pip install slither-analyzer
    - name: Run Slither
      run: slither . --fail-high
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm install
    - run: npm run lint
    - run: npm run solhint
    - run: npm test
    - run: npx hardhat coverage
